import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../core/constants.dart';
import '../core/format.dart';
import '../data/models/models.dart';

/// Printable documents: the case sheet, the prescription slip, the day list
/// and the stock report.
///
/// Everything is laid out for A4 because that is what the clinic's printer
/// holds, and generated as bytes so the caller decides where they land.
class PdfService {
  PdfService({required this.clinicName});

  final String clinicName;

  pw.Font? _base;
  pw.Font? _bold;
  pw.Font? _devanagari;

  /// Loads the embedded faces once per run.
  ///
  /// The body text uses Noto Sans rather than one of the PDF standard faces:
  /// those are limited to WinAnsi, which would silently drop an em dash and,
  /// far worse, mangle any patient name that is not plain Latin. Kalam carries
  /// the Devanagari in the clinic's own name.
  ///
  /// If an asset cannot be read the standard faces are used instead, because a
  /// report that prints imperfectly beats a report that does not print.
  Future<void> _ensureFonts() async {
    if (_base != null) return;
    _base = await _load('assets/fonts/NotoSans-Regular.ttf') ??
        pw.Font.helvetica();
    _bold =
        await _load('assets/fonts/NotoSans-Bold.ttf') ?? pw.Font.helveticaBold();
    _devanagari = await _load('assets/fonts/Kalam-Regular.ttf');
  }

  Future<pw.Font?> _load(String asset) async {
    try {
      return pw.Font.ttf(await rootBundle.load(asset));
    } catch (_) {
      return null;
    }
  }

  pw.ThemeData get _theme => pw.ThemeData.withFont(
        base: _base,
        bold: _bold,
        fontFallback: [?_devanagari],
      );

  static const PdfColor _ink = PdfColor.fromInt(0xFF1A1A1A);
  static const PdfColor _muted = PdfColor.fromInt(0xFF6B6B6B);
  static const PdfColor _rule = PdfColor.fromInt(0xFFD6D6D6);
  static const PdfColor _accent = PdfColor.fromInt(0xFF0F6CBD);

  pw.Widget _letterhead(String documentTitle, {String? subtitle}) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  clinicName,
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                    color: _ink,
                  ),
                ),
                pw.SizedBox(height: 2),
                pw.Text(
                  'Project सत्र · clinic record',
                  // Named explicitly rather than left to font fallback: the
                  // standard PDF faces carry no Devanagari, and a clinic's own
                  // letterhead is not the place to discover that.
                  style: pw.TextStyle(
                    fontSize: 9,
                    color: _muted,
                    font: _devanagari,
                  ),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  documentTitle.toUpperCase(),
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                    color: _accent,
                    letterSpacing: 1.2,
                  ),
                ),
                if (subtitle != null)
                  pw.Text(subtitle,
                      style: pw.TextStyle(fontSize: 9, color: _muted)),
                pw.Text(
                  'Printed ${fmtDateTime(DateTime.now())}',
                  style: pw.TextStyle(fontSize: 8, color: _muted),
                ),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Divider(color: _rule, thickness: 1),
      ],
    );
  }

  pw.Widget _footer(pw.Context context) => pw.Column(
        children: [
          pw.Divider(color: _rule, thickness: 0.5),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Project सत्र — open-source clinic management',
                style: pw.TextStyle(
                  fontSize: 7,
                  color: _muted,
                  font: _devanagari,
                ),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(fontSize: 7, color: _muted),
              ),
            ],
          ),
        ],
      );

  pw.Widget _sectionTitle(String text) => pw.Padding(
        padding: const pw.EdgeInsets.only(top: 14, bottom: 6),
        child: pw.Text(
          text,
          style: pw.TextStyle(
            fontSize: 11,
            fontWeight: pw.FontWeight.bold,
            color: _ink,
          ),
        ),
      );

  pw.Widget _field(String label, String value, {double width = 130}) =>
      pw.SizedBox(
        width: width,
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(label.toUpperCase(),
                style: pw.TextStyle(fontSize: 7, color: _muted, letterSpacing: 0.6)),
            pw.SizedBox(height: 2),
            pw.Text(value.isEmpty ? '—' : value,
                style: const pw.TextStyle(fontSize: 10, color: _ink)),
          ],
        ),
      );

  /// The full case sheet: who the patient is, every consultation, the symptom
  /// grid as it stood each time, and what was prescribed.
  Future<Uint8List> patientCaseSheet({
    required Patient patient,
    required List<Visit> visits,
    required Map<String, List<SymptomReading>> readingsByVisit,
    required List<Prescription> prescriptions,
    required Map<String, List<PrescriptionItem>> itemsByPrescription,
    required Map<String, Medicine> medicines,
    required Map<String, Staff> staff,
  }) async {
    await _ensureFonts();
    final doc = pw.Document(theme: _theme, title: 'Case sheet ${patient.code}');

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(32, 28, 32, 24),
        header: (_) => _letterhead('Case sheet', subtitle: patient.code),
        footer: _footer,
        build: (context) => [
          pw.SizedBox(height: 10),
          pw.Text(patient.name,
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),
          pw.Wrap(
            spacing: 12,
            runSpacing: 10,
            children: [
              _field('Record no.', patient.code, width: 90),
              _field('Age', patient.age == null ? '—' : '${patient.age}', width: 60),
              _field('Sex', patient.sex.label, width: 70),
              _field('Weight', fmtWeight(patient.weightKg), width: 80),
              _field('Phone', patient.phone ?? '—', width: 110),
              _field('Registered', fmtDate(patient.registeredAt), width: 100),
              _field(
                'Under care of',
                staff[patient.assignedTo]?.fullName ?? 'Unassigned',
                width: 140,
              ),
            ],
          ),
          pw.SizedBox(height: 10),
          _field('Address', patient.address ?? '—', width: 520),
          if ((patient.chiefComplaints ?? '').isNotEmpty) ...[
            _sectionTitle('Chief complaints'),
            pw.Text(patient.chiefComplaints!,
                style: const pw.TextStyle(fontSize: 10)),
          ],
          if (visits.isEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 18),
              child: pw.Text('No consultations recorded yet.',
                  style: pw.TextStyle(fontSize: 10, color: _muted)),
            ),
          for (final visit in visits) ...[
            _sectionTitle('Consultation — ${fmtDateTime(visit.visitedAt)}'),
            pw.Wrap(spacing: 12, runSpacing: 8, children: [
              _field('Seen by',
                  staff[visit.recordedBy]?.fullName ?? '—', width: 140),
              _field('Weight', fmtWeight(visit.weightKg), width: 80),
            ]),
            if ((visit.chiefComplaints ?? '').isNotEmpty)
              pw.Padding(
                padding: const pw.EdgeInsets.only(top: 6),
                child: pw.Text('Complaints: ${visit.chiefComplaints}',
                    style: const pw.TextStyle(fontSize: 10)),
              ),
            if ((visit.findings ?? '').isNotEmpty)
              pw.Padding(
                padding: const pw.EdgeInsets.only(top: 4),
                child: pw.Text('Findings: ${visit.findings}',
                    style: const pw.TextStyle(fontSize: 10)),
              ),
            if ((visit.advice ?? '').isNotEmpty)
              pw.Padding(
                padding: const pw.EdgeInsets.only(top: 4),
                child: pw.Text('Advice: ${visit.advice}',
                    style: const pw.TextStyle(fontSize: 10)),
              ),
            pw.SizedBox(height: 8),
            _symptomTable(readingsByVisit[visit.id] ?? const []),
          ],
          if (prescriptions.isNotEmpty) _sectionTitle('Prescriptions'),
          for (final prescription in prescriptions)
            _prescriptionBlock(
              prescription,
              itemsByPrescription[prescription.id] ?? const [],
              medicines,
              staff,
            ),
        ],
      ),
    );
    return doc.save();
  }

  pw.Widget _symptomTable(List<SymptomReading> readings) {
    if (readings.isEmpty) {
      return pw.Text('No symptom grid recorded for this consultation.',
          style: pw.TextStyle(fontSize: 9, color: _muted));
    }
    final byKey = {for (final r in readings) r.key: r};
    final rows = <List<String>>[];
    for (final def in kSymptoms) {
      final reading = byKey[def.key];
      if (reading == null) continue;
      rows.add([
        def.label,
        def.isDate ? fmtDate(parseIsoDate(reading.value)) : titleCase(reading.value),
      ]);
    }
    if (rows.isEmpty) {
      return pw.Text('No symptom grid recorded for this consultation.',
          style: pw.TextStyle(fontSize: 9, color: _muted));
    }
    return pw.TableHelper.fromTextArray(
      headers: const ['Symptom', 'Recorded'],
      data: rows,
      border: pw.TableBorder.all(color: _rule, width: 0.5),
      headerStyle: pw.TextStyle(
        fontSize: 8,
        fontWeight: pw.FontWeight.bold,
        color: _ink,
      ),
      headerDecoration: const pw.BoxDecoration(
        color: PdfColor.fromInt(0xFFF2F4F7),
      ),
      cellStyle: const pw.TextStyle(fontSize: 9),
      cellAlignment: pw.Alignment.centerLeft,
      columnWidths: {
        0: const pw.FlexColumnWidth(1),
        1: const pw.FlexColumnWidth(1.4),
      },
    );
  }

  pw.Widget _prescriptionBlock(
    Prescription prescription,
    List<PrescriptionItem> items,
    Map<String, Medicine> medicines,
    Map<String, Staff> staff,
  ) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: _rule, width: 0.5),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(fmtDateTime(prescription.prescribedAt),
                  style: pw.TextStyle(
                      fontSize: 10, fontWeight: pw.FontWeight.bold)),
              pw.Text(
                prescription.dispensed ? 'Dispensed' : 'Not yet dispensed',
                style: pw.TextStyle(
                  fontSize: 8,
                  color: prescription.dispensed ? _accent : _muted,
                ),
              ),
            ],
          ),
          pw.Text(
            'Prescribed by ${staff[prescription.prescribedBy]?.fullName ?? '—'}',
            style: pw.TextStyle(fontSize: 8, color: _muted),
          ),
          pw.SizedBox(height: 6),
          pw.TableHelper.fromTextArray(
            headers: const ['Medicine', 'Dose', 'Days', 'Qty', 'Instructions'],
            data: [
              for (final item in items)
                [
                  medicines[item.medicineId]?.displayName ?? 'Unknown medicine',
                  '${item.dose.code} (${item.dose.description})',
                  '${item.durationDays}',
                  '${item.quantity}',
                  item.instructions ?? '—',
                ],
            ],
            border: pw.TableBorder.all(color: _rule, width: 0.5),
            headerStyle:
                pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
            headerDecoration:
                const pw.BoxDecoration(color: PdfColor.fromInt(0xFFF2F4F7)),
            cellStyle: const pw.TextStyle(fontSize: 9),
            cellAlignment: pw.Alignment.centerLeft,
            columnWidths: {
              0: const pw.FlexColumnWidth(2.2),
              1: const pw.FlexColumnWidth(1.6),
              2: const pw.FlexColumnWidth(0.6),
              3: const pw.FlexColumnWidth(0.6),
              4: const pw.FlexColumnWidth(2),
            },
          ),
          if ((prescription.notes ?? '').isNotEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 6),
              child: pw.Text('Note: ${prescription.notes}',
                  style: const pw.TextStyle(fontSize: 9)),
            ),
        ],
      ),
    );
  }

  /// A single slip to hand to the patient at the counter.
  Future<Uint8List> prescriptionSlip({
    required Patient patient,
    required Prescription prescription,
    required List<PrescriptionItem> items,
    required Map<String, Medicine> medicines,
    Staff? prescriber,
  }) async {
    await _ensureFonts();
    final doc = pw.Document(theme: _theme, title: 'Prescription');

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a5,
        margin: const pw.EdgeInsets.all(24),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _letterhead('Prescription', subtitle: patient.code),
            pw.SizedBox(height: 12),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                _field('Patient', patient.name, width: 180),
                _field(
                  'Age / Sex',
                  '${patient.age ?? '—'} / ${patient.sex.short}',
                  width: 70,
                ),
                _field('Date', fmtDate(prescription.prescribedAt), width: 90),
              ],
            ),
            pw.SizedBox(height: 14),
            pw.TableHelper.fromTextArray(
              headers: const ['Rx', 'Dose', 'Days', 'Qty'],
              data: [
                for (final item in items)
                  [
                    medicines[item.medicineId]?.displayName ?? '—',
                    item.dose.code,
                    '${item.durationDays}',
                    '${item.quantity}',
                  ],
              ],
              border: pw.TableBorder.all(color: _rule, width: 0.5),
              headerStyle:
                  pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold),
              headerDecoration:
                  const pw.BoxDecoration(color: PdfColor.fromInt(0xFFF2F4F7)),
              cellStyle: const pw.TextStyle(fontSize: 10),
              cellAlignment: pw.Alignment.centerLeft,
              columnWidths: {
                0: const pw.FlexColumnWidth(3),
                1: const pw.FlexColumnWidth(1),
                2: const pw.FlexColumnWidth(0.8),
                3: const pw.FlexColumnWidth(0.8),
              },
            ),
            if ((prescription.notes ?? '').isNotEmpty) ...[
              pw.SizedBox(height: 10),
              pw.Text(prescription.notes!,
                  style: const pw.TextStyle(fontSize: 9)),
            ],
            pw.Spacer(),
            pw.Align(
              alignment: pw.Alignment.centerRight,
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.center,
                children: [
                  pw.Container(width: 150, height: 0.6, color: _rule),
                  pw.SizedBox(height: 3),
                  pw.Text(prescriber?.fullName ?? '',
                      style: pw.TextStyle(
                          fontSize: 9, fontWeight: pw.FontWeight.bold)),
                  pw.Text(prescriber?.speciality ?? 'Healthcare provider',
                      style: pw.TextStyle(fontSize: 8, color: _muted)),
                ],
              ),
            ),
          ],
        ),
      ),
    );
    return doc.save();
  }

  /// The list the front desk works from.
  Future<Uint8List> daySchedule({
    required DateTime day,
    required List<Appointment> appointments,
    required Map<String, Patient> patients,
    required Map<String, Staff> staff,
  }) async {
    await _ensureFonts();
    final doc = pw.Document(theme: _theme, title: 'Schedule ${isoDate(day)}');

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(32, 28, 32, 24),
        header: (_) => _letterhead('Day schedule', subtitle: fmtDay(day)),
        footer: _footer,
        build: (context) => [
          pw.SizedBox(height: 12),
          if (appointments.isEmpty)
            pw.Text('Nothing booked for this day.',
                style: pw.TextStyle(fontSize: 10, color: _muted))
          else
            pw.TableHelper.fromTextArray(
              headers: const [
                'Time',
                'Patient',
                'Record no.',
                'With',
                'Reason',
                'Status',
              ],
              data: [
                for (final a in appointments)
                  [
                    fmtTime(a.scheduledAt),
                    patients[a.patientId]?.name ?? 'Unknown',
                    patients[a.patientId]?.code ?? '—',
                    staff[a.staffId]?.fullName ?? 'Unassigned',
                    a.reason ?? '—',
                    a.status.label,
                  ],
              ],
              border: pw.TableBorder.all(color: _rule, width: 0.5),
              headerStyle:
                  pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
              headerDecoration:
                  const pw.BoxDecoration(color: PdfColor.fromInt(0xFFF2F4F7)),
              cellStyle: const pw.TextStyle(fontSize: 9),
              cellAlignment: pw.Alignment.centerLeft,
              columnWidths: {
                0: const pw.FlexColumnWidth(0.8),
                1: const pw.FlexColumnWidth(2),
                2: const pw.FlexColumnWidth(1),
                3: const pw.FlexColumnWidth(1.6),
                4: const pw.FlexColumnWidth(2),
                5: const pw.FlexColumnWidth(1),
              },
            ),
        ],
      ),
    );
    return doc.save();
  }

  /// Stock on hand, with the short items called out first.
  Future<Uint8List> inventoryReport(List<Medicine> medicines) async {
    await _ensureFonts();
    final doc = pw.Document(theme: _theme, title: 'Stock report');
    final low = medicines.where((m) => m.isLow).toList();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(32, 28, 32, 24),
        header: (_) => _letterhead('Stock report'),
        footer: _footer,
        build: (context) => [
          pw.SizedBox(height: 12),
          if (low.isNotEmpty) ...[
            _sectionTitle('Needs reordering (${low.length})'),
            pw.TableHelper.fromTextArray(
              headers: const ['Medicine', 'On hand', 'Reorder at'],
              data: [
                for (final m in low)
                  [m.displayName, '${m.stockQty} ${m.unit}', '${m.reorderLevel}'],
              ],
              border: pw.TableBorder.all(color: _rule, width: 0.5),
              headerStyle:
                  pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
              headerDecoration:
                  const pw.BoxDecoration(color: PdfColor.fromInt(0xFFFDECEA)),
              cellStyle: const pw.TextStyle(fontSize: 9),
              cellAlignment: pw.Alignment.centerLeft,
            ),
          ],
          _sectionTitle('Full formulary (${medicines.length})'),
          pw.TableHelper.fromTextArray(
            headers: const ['Medicine', 'Form', 'On hand', 'Reorder at'],
            data: [
              for (final m in medicines)
                [
                  m.name,
                  m.form.label,
                  '${m.stockQty} ${m.unit}',
                  '${m.reorderLevel}',
                ],
            ],
            border: pw.TableBorder.all(color: _rule, width: 0.5),
            headerStyle:
                pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
            headerDecoration:
                const pw.BoxDecoration(color: PdfColor.fromInt(0xFFF2F4F7)),
            cellStyle: const pw.TextStyle(fontSize: 9),
            cellAlignment: pw.Alignment.centerLeft,
          ),
        ],
      ),
    );
    return doc.save();
  }

  /// Writes [bytes] to [path], creating the folder if needed.
  static Future<File> writeTo(String path, Uint8List bytes) async {
    final file = File(path);
    await file.parent.create(recursive: true);
    await file.writeAsBytes(bytes);
    return file;
  }
}
